# Generated by Django 3.0.5 on 2020-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquestrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='no description', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='no description', max_length=30),
        ),
    ]
