# Generated by Django 3.0.5 on 2020-06-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquestrequest', '0002_auto_20200609_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requestID',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
